# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-09 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idgo_admin', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
        ('auth_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contributions',
            field=models.ManyToManyField(related_name='profile_contributions', through='idgo_admin.LiaisonsContributeurs', to='idgo_admin.Organisation', verbose_name="Organisations dont l'utilisateur est contributeur"),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='idgo_admin.Organisation', verbose_name="Organisation d'appartenance"),
        ),
        migrations.AddField(
            model_name='user',
            name='referents',
            field=models.ManyToManyField(related_name='profile_referents', through='idgo_admin.LiaisonsReferents', to='idgo_admin.Organisation', verbose_name="Organisations dont l'utilisateur est réferent"),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(to='idgo_admin.Role'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='gdpruser',
            unique_together=set([('user', 'gdpr')]),
        ),
    ]
